// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DemoService.proto

package com.xiaolanhe;

public interface RequestDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
